### PR TITLE
Update explainer to reference HTML spec and redirect spec to explainer

### PR DESCRIPTION
**Pull request by pmeenan**
This strips out all of the spec language from the spec, adds a note about it being obsolete and with references to the explainer and uses a javascript redirect to redirect to the explainer.  It also updates the canonical URL to the explainer.

The explainer was modified to point to the relevant parts of the HTML spec for the fetchpriority attributes.

### CODE REVIEW

**Review by yoavweiss — APPROVED** [review]
LGTM

**Comment by yoavweiss** [comment]
The bots seem unhappy with this... Can you take a look?

**Comment by pmeenan** [comment]
Sorry for the spam, working on it.  Bizarre because bikeshed work locally and produces the html with the same command-line so trying to figure out what's going on.

**Comment by pmeenan** [comment]
Finally narrowed it down to the redirect itself. Something in the CI version of the build must try loading the resulting HTML page because no form of redirect would pass (including a convoluted eval in a timer) but keeping it simple and only applying the redirect when on the production HTML origin seems to pass the build and work.

**Pull request merged**
