### PR TITLE
camel-case the fetchPriority IDL attribute.

### LINKED ISSUE #68: fetchpriority IDL attribute should be fetchPriority
See [W3C TAG Design Principles](https://w3ctag.github.io/design-principles/#:~:text=Note%20that%20in%20particular%2C%20when%20a%20HTML%20attribute%20is%20reflected%20as%20a%20property%2C%20the%20attribute%20and%20property%E2%80%99s%20casings%20won%E2%80%99t%20necessarily%20match)

### PR DESCRIPTION
**Pull request by pmeenan**
Fix #68

### CODE REVIEW

**Comment by pmeenan** [comment]
@[domenic](https://github.com/domenic) could you PTAL and see if this catches all of the IDL references that should be camel-cased (particularly in the processing model steps)?

**Comment by domenic** [comment]
This looks perfect. The processing model steps refer to the content attribute, not IDL attribute, and so don't need any casing updates.

(You could separately update them to use `<{img/fetchpriority}>` syntax, to make this clearer and get a nice cross-link, but that's just an editorial issue.)

**Comment by foolip** [comment]
I noticed this rename in https://github.com/web-platform-tests/wpt/pull/33731 and the all-lowercase variants are in BCD since https://github.com/mdn/browser-compat-data/pull/15489.

The all-lowercase attributes are just about to be released in Chrome stable, and remain all-lowercase in Chromium master. Oops?

This mishap is probably too late to prevent, so we'll have to update BCD to record it as an alternative name.

@pmeenan can you take care of updating Chromium? Now that this feature has shipped, it might also be a good time to start requiring browser bugs and tests for all changes to the spec, to avoid this happening.

**Comment by pmeenan** [comment]
@foolip yep, thanks. Luckily most early adopters are just using the attribute in markup where case doesn't matter.

**Pull request merged**
